# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('assistance', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=300)),
                ('housing', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=300)),
            ],
        ),
    ]
